package BombermenClientServerInterfaces.Messaging;

public enum CommandCode {
	MOVE,
	DROP_BOMB,
	BOMB_EXPLODE,
	BOMB_COLLISION,
	PLAYER_LOGIN,
	PLAYER_LOGIN_SUCCESS,
	PLAYER_LOGIN_ERROR,
	PLAYER_EXIT,
	PLAYER_GOODBYE,
	LOAD_LABYRINTH,
	ERROR_CODE,
	SERVER_FULL,
}
