package BombermenClientServerInterfaces.Messaging;

public enum CommandCode {
	MOVE,
	DROP_BOMB,
	BOMB_COLLISION,
	BOMB_EXPLODE,
	SERVER_LOGGING_MESSAGES,
	PLAYER_LOGIN,
	PLAYER_EXIT,
	PLAYER_LOGIN_ERROR,
	LOAD_LABYRINTH,
	ERROR_CODE
}
